'use client';
import {useState,useTransition} from 'react';
import {resumeMatch,setMatchPlayerSelection} from './actions';
type Player={player_id:string;team_id:string;jcm_players:{id:string;first_name:string;surname:string}|{id:string;first_name:string;surname:string}[]|null};type Selected={player_id:string;team_id:string;selected:boolean};type Team={id:string;name:string};
function playerName(p:Player){const x=Array.isArray(p.jcm_players)?p.jcm_players[0]:p.jcm_players;return x?x.first_name+' '+x.surname:'Unknown player'}
export function MatchSquadClient({matchId,home,away,homePlayers,awayPlayers,selections,availability:_availability,onResume}:{matchId:string;home:Team;away:Team;homePlayers:Player[];awayPlayers:Player[];selections:Selected[];availability?:unknown[];onResume?:(homeIds:string[],awayIds:string[])=>void}){
 const homePlayerIds=new Set(homePlayers.map(p=>p.player_id));const awayPlayerIds=new Set(awayPlayers.map(p=>p.player_id));const initialHome=selections.filter(s=>s.team_id===home.id&&s.selected&&homePlayerIds.has(s.player_id)).map(s=>s.player_id);const initialAway=selections.filter(s=>s.team_id===away.id&&s.selected&&awayPlayerIds.has(s.player_id)).map(s=>s.player_id);const[homeSet,setHomeSet]=useState(new Set(initialHome));const[awaySet,setAwaySet]=useState(new Set(initialAway));const[pending,start]=useTransition();const[msg,setMsg]=useState('');
 function toggle(team:'home'|'away',id:string){const setter=team==='home'?setHomeSet:setAwaySet;setter(prev=>{const next=new Set(prev);if(next.has(id))next.delete(id);else if(next.size<14)next.add(id);return next})}
 async function confirm(){if(homeSet.size<6||homeSet.size>14||awaySet.size<6||awaySet.size>14){setMsg('Each team must have between 6 and 14 selected players.');return}start(async()=>{const fd=new FormData();fd.set('match_id',matchId);homeSet.forEach(id=>fd.append('team_a_player_ids',id));awaySet.forEach(id=>fd.append('team_b_player_ids',id));const r=await resumeMatch(fd);setMsg(r.message);if(r.ok)onResume?.(safeHomeIds,safeAwayIds)})}
 function teamBlock(team:Team,players:Player[],chosen:Set<string>,kind:'home'|'away'){return <section className="card squad-team"><div className="section-title">{team.name}<span className="count">{chosen.size} selected · {players.length} registered</span></div><p className="form-help">Select the players available to the scorer for this match session.</p><div className="table-wrap squad-table-wrap"><table className="squad-table"><thead><tr><th>Player</th><th>Playing</th></tr></thead><tbody>{players.map(p=>{const yes=chosen.has(p.player_id);return <tr key={p.player_id}><td><strong>{playerName(p)}</strong></td><td><button type="button" className={yes?'button':'secondary-button'} disabled={pending||(!yes&&chosen.size>=14)} onClick={()=>toggle(kind,p.player_id)}>{yes?'Selected':'Select'}</button></td></tr>})}</tbody></table></div><div style={{marginTop:12,fontWeight:800}}>{chosen.size<6?'Select at least 6 players':chosen.size===14?'Maximum 14 selected':'Valid squad'} · {chosen.size}/14</div></section>}
 return <section className="section"><div className="eyebrow">Playing squad</div><h2>Select match players</h2><p className="subtitle">The scorer or coach selects 6–14 players for each team. Parent availability is information only. This selection is saved directly to Supabase as a match session and is required again whenever the match is resumed.</p><div className="grid" style={{marginBottom:16}}><div className="card"><div className="stat-label">{home.name}</div><div className="stat">{homeSet.size}/14</div></div><div className="card"><div className="stat-label">{away.name}</div><div className="stat">{awaySet.size}/14</div></div></div><div className="admin-grid squad-grid">{teamBlock(home,homePlayers,homeSet,'home')}{teamBlock(away,awayPlayers,awaySet,'away')}</div><div className="card" style={{marginTop:16}}><button className="button" disabled={pending||homeSet.size<6||homeSet.size>14||awaySet.size<6||awaySet.size>14} onClick={confirm}>{pending?'Saving…':'Save squad & continue'}</button>{msg&&<div className="success" style={{marginTop:12}}>{msg}</div>}</div></section>
}
