'use server';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';

async function actor(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Authentication required.');const[{data:system},{data:schoolRoles}]=await Promise.all([supabase.from('jcm_user_roles').select('role').eq('user_id',user.id).eq('role','SYSTEM_ADMIN').eq('active',true).maybeSingle(),supabase.from('jcm_school_users').select('school_id,role').eq('user_id',user.id).eq('active',true).in('role',['SCHOOL_ADMIN','COACH'])]);if(!system&&!schoolRoles?.length)throw new Error('Player management access required.');return{supabase,user,isSystemAdmin:!!system,schoolIds:(schoolRoles??[]).map(x=>x.school_id)};}

export async function createPlayer(formData:FormData){const{supabase,isSystemAdmin,schoolIds}=await actor();const schoolId=String(formData.get('school_id')??'');const firstName=String(formData.get('first_name')??'').trim();const surname=String(formData.get('surname')??'').trim();const dob=String(formData.get('date_of_birth')??'').trim();const gender=String(formData.get('gender')??'').trim();const teamId=String(formData.get('team_id')??'');if(!schoolId||!firstName||!surname)return{ok:false,message:'School, first name and surname are required.'};if(!isSystemAdmin&&!schoolIds.includes(schoolId))return{ok:false,message:'You can only manage players for your own school.'};if(teamId){const{data:team}=await supabase.from('jcm_teams').select('id,school_id,season_id,name,status').eq('id',teamId).maybeSingle();if(!team||team.school_id!==schoolId)return{ok:false,message:'Selected team is invalid for this school.'};if(team.status==='RETIRED')return{ok:false,message:'Retired teams cannot receive new players.'};}const{data:player,error}=await supabase.from('jcm_players').insert({school_id:schoolId,first_name:firstName,surname,date_of_birth:dob||null,gender:gender||null}).select('id').single();if(error)return{ok:false,message:error.message};if(teamId){const{data:team}=await supabase.from('jcm_teams').select('id,season_id,name').eq('id',teamId).single();if(team){const{error:assignmentError}=await supabase.from('jcm_team_players').insert({team_id:team.id,player_id:player.id,season_id:team.season_id});if(assignmentError)return{ok:false,message:`Player was registered, but team assignment failed: ${assignmentError.message}`};}}revalidatePath('/admin/players');revalidatePath('/school');return{ok:true,message:teamId?`${firstName} ${surname} was added to the selected team.`:`${firstName} ${surname} was added.`};}

export async function assignPlayerToTeam(formData:FormData){const{supabase,isSystemAdmin,schoolIds}=await actor();const playerId=String(formData.get('player_id')??'');const teamId=String(formData.get('team_id')??'');if(!playerId||!teamId)return{ok:false,message:'Player and team are required.'};const[{data:player},{data:team}]=await Promise.all([supabase.from('jcm_players').select('school_id').eq('id',playerId).maybeSingle(),supabase.from('jcm_teams').select('id,school_id,season_id,name,status').eq('id',teamId).maybeSingle()]);if(!player||!team)return{ok:false,message:'Player or team could not be found.'};if(player.school_id!==team.school_id)return{ok:false,message:'A player can only be assigned to a team from the same school.'};if(!isSystemAdmin&&!schoolIds.includes(team.school_id))return{ok:false,message:'You can only manage your own school.'};if(team.status==='RETIRED')return{ok:false,message:'Retired teams cannot receive new players.'};const{error}=await supabase.from('jcm_team_players').insert({team_id:team.id,player_id:playerId,season_id:team.season_id});if(error)return{ok:false,message:error.message};revalidatePath('/admin/players');revalidatePath('/school');return{ok:true,message:`Player assigned to ${team.name}.`};}
