'use client';
import {useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';

type Player={id:string;team_id:string;batting_order:number|null;name:string};
type Match={id:string;team_a_id:string;team_b_id:string;age_group:string;ruleset:string;status:string};
type State={match_id:string;innings_id:string|null;striker_id:string|null;non_striker_id:string|null;current_bowler_id:string|null;batting_pair_id:string|null;over_no:number;over_ball_count:number;pair_ball_count:number;batter_ball_count:number;pending_workflow:string|null;workflow_state:any;state_version:number};
type Innings={id:string;innings_no:number;batting_team_id:string;fielding_team_id:string;runs:number;wickets:number;legal_balls:number;total_balls:number;completed:boolean;target:number|null};
type Stat={innings_no:number;player_id:string;runs:number;balls:number;fours:number;sixes:number;wides:number;no_balls:number;coach_runs:number;unplayable_balls:number;wickets:number;retired:boolean};

export function ScoringClient({match,initialState,initialInnings,players,initialEvents,initialStats}:{match:Match;initialState:State;initialInnings:Innings[];players:Player[];initialEvents:any[];initialStats:Stat[]}){
 const supabase=createClient();
 const [state,setState]=useState(initialState);const [innings,setInnings]=useState(initialInnings);const [events,setEvents]=useState(initialEvents);const [stats,setStats]=useState(initialStats);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 const [setup,setSetup]=useState({striker:'',non:'',bowler:''});const [replace,setReplace]=useState('');const [dismissal,setDismissal]=useState('BOWLED');const [fielder,setFielder]=useState('');
 const current=innings.find(i=>i.id===state.innings_id)??innings[0];const battingPlayers=players.filter(p=>p.team_id===current?.batting_team_id);const fieldingPlayers=players.filter(p=>p.team_id===current?.fielding_team_id);const name=(id:string|null)=>players.find(p=>p.id===id)?.name??'—';
 const strikerStat=stats.find(s=>s.innings_no===current?.innings_no&&s.player_id===state.striker_id);const nonStat=stats.find(s=>s.innings_no===current?.innings_no&&s.player_id===state.non_striker_id);
 const rules=useMemo(()=>match.ruleset==='U6'?{over:8,pair:16,max:undefined,coach:true}:{over:match.ruleset==='U7'?6:5,pair:match.ruleset==='U7'?24:undefined,max:match.ruleset==='U8'?80:undefined,coach:match.ruleset!=='U8'},[match.ruleset]);
 async function refresh(){const [s,i,e,st]=await Promise.all([supabase.from('jcm_match_state').select('*').eq('match_id',match.id).single(),supabase.from('jcm_innings').select('*').eq('match_id',match.id).order('innings_no'),supabase.from('jcm_scoring_events').select('id,sequence_number,event_type,runs,extras,dismissal_type,created_at').eq('match_id',match.id).order('sequence_number',{ascending:false}).limit(30),supabase.from('jcm_player_match_stats').select('*').eq('match_id',match.id)]);if(s)dataState(s);if(i.data)setInnings(i.data as Innings[]);if(e.data)setEvents(e.data);if(st.data)setStats(st.data as Stat[])}
 function dataState(s:any){setState(s as State)}
 async function event(type:string,payload:any={}){setBusy(true);setMsg('');const {data,error}=await supabase.rpc('jcm_process_scoring_event',{p_match_id:match.id,p_event_type:type,p_payload:{...payload,expected_state_version:state.state_version},p_client_event_id:crypto.randomUUID()});if(error){setMsg(error.message);setBusy(false);return null}if(data?.state)dataState(data.state);await refresh();setBusy(false);return data}
 async function start(){if(!setup.striker||!setup.non||!setup.bowler){setMsg('Select two batters and a bowler.');return}await event('START_INNINGS',{batting_team_id:current.batting_team_id,fielding_team_id:current.fielding_team_id,striker_id:setup.striker,non_striker_id:setup.non,bowler_id:setup.bowler});}
 async function undo(){setBusy(true);const {data,error}=await supabase.rpc('jcm_undo_last_scoring_event',{p_match_id:match.id});if(error)setMsg(error.message);else if(data?.state)dataState(data.state);await refresh();setBusy(false)}
 async function run(r:number){await event('RUN',{runs:r})}
 async function wide(completed=0){await event('WIDE',{wide_runs:1,completed_runs:completed})}
 async function noBall(completed=0){await event('NO_BALL',{no_ball_runs:1,completed_runs:completed})}
 async function wicket(type:string){await event('WICKET',{dismissed_player_id:state.striker_id,dismissal_type:type,fielder_id:fielder||null,runs:0,legal_ball:true})}
 async function runOut(){await event('RUN_OUT',{dismissed_player_id:state.striker_id,dismissal_type:'RUN_OUT',fielder_id:fielder||null,runs:0,legal_ball:false,counts_as_delivery:false})}
 async function replaceBatter(){const retired=state.workflow_state?.retired_player_id??state.workflow_state?.dismissed_player_id??state.striker_id;if(!replace){setMsg('Select the new batter.');return}await event('REPLACE_BATTER',{new_batter_id:replace,replaces_player_id:retired})}
 async function completeInnings(){await event('INNINGS_COMPLETE')}
 async function targetAction(action:'END_MATCH'|'PLAY_ON'){await event('TARGET_DECISION',{action})}
 const targetReached=current?.innings_no===2&&current.target!=null&&current.runs>=current.target;
 const needsSetup=state.pending_workflow==='READY_TO_START'||state.pending_workflow==='INNINGS_2_SETUP'||!state.striker_id;
 const needsBowler=state.pending_workflow==='BOWLER_REQUIRED'||(!state.current_bowler_id&&!needsSetup);
 const needsReplacement=state.pending_workflow==='BATTER_REPLACEMENT';
 const completed=match.status==='COMPLETED'||state.pending_workflow==='MATCH_COMPLETE';
 const activeBatters=[state.striker_id,state.non_striker_id].filter(Boolean);
 const replacementOptions=battingPlayers.filter(p=>!activeBatters.includes(p.id)&&!stats.some(s=>s.innings_no===current?.innings_no&&s.player_id===p.id&&s.retired));
 return <div className="scoring-shell">
   <div className="score-hero"><div><div className="eyebrow">Live scoring · {match.ruleset}</div><div className="score-main">{current?.runs??0}/{current?.wickets??0}</div><div className="score-meta">Over {state.over_no} · {state.over_ball_count}/{rules.over} legal balls {current?.target?`· Target ${current.target}`:''}</div></div><div className="score-side"><span>{name(state.striker_id)}*</span><span>{name(state.non_striker_id)}</span><span>Bowler: {name(state.current_bowler_id)}</span></div></div>
   {msg&&<div className="error">{msg}</div>}
   {needsSetup&&<section className="card section"><div className="section-title">Start {current?.innings_no===2?'innings 2':'innings 1'}</div><p className="form-help">Choose the two opening batters and the current bowler. This is saved to the backend before scoring begins.</p><div className="scoring-setup-grid"><div className="field"><label>Striker</label><select value={setup.striker} onChange={e=>setSetup({...setup,striker:e.target.value})}><option value="">Select…</option>{battingPlayers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Non-striker</label><select value={setup.non} onChange={e=>setSetup({...setup,non:e.target.value})}><option value="">Select…</option>{battingPlayers.filter(p=>p.id!==setup.striker).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Bowler</label><select value={setup.bowler} onChange={e=>setSetup({...setup,bowler:e.target.value})}><option value="">Select…</option>{fieldingPlayers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></div><button className="button" disabled={busy} onClick={start}>{busy?'Starting…':'Start innings'}</button></section>}
   {!needsSetup&&needsBowler&&!completed&&<section className="card section"><div className="section-title">Next over — select bowler</div><div className="field"><label>Bowler</label><select value={setup.bowler} onChange={e=>setSetup({...setup,bowler:e.target.value})}><option value="">Select…</option>{fieldingPlayers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><button className="button" disabled={busy||!setup.bowler} onClick={()=>event('SET_BOWLER',{bowler_id:setup.bowler})}>Set bowler</button></section>}
   {needsReplacement&&!completed&&<section className="card section"><div className="section-title">New batter required</div><p className="form-help">Select the player replacing {name(state.workflow_state?.retired_player_id??state.workflow_state?.dismissed_player_id??state.striker_id)}.</p><div className="field"><label>New batter</label><select value={replace} onChange={e=>setReplace(e.target.value)}><option value="">Select…</option>{replacementOptions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><button className="button" disabled={busy||!replace} onClick={replaceBatter}>Confirm new batter</button></section>}
   {targetReached&&!completed&&<section className="card section target-card"><div className="section-title">Target reached</div><p>The batting team has reached the target. Choose whether to finish or continue so more players can receive batting opportunity.</p><div className="action-row"><button className="button" disabled={busy} onClick={()=>targetAction('END_MATCH')}>End match</button><button className="secondary-button big" disabled={busy} onClick={()=>targetAction('PLAY_ON')}>Play on</button></div></section>}
   {!needsSetup&&!needsBowler&&!needsReplacement&&!targetReached&&!completed&&<>
    <section className="card section"><div className="section-title">Score</div><div className="run-grid">{[0,1,2,3,4,6].map(r=><button key={r} className="score-button" disabled={busy} onClick={()=>run(r)}>{r}</button>)}</div><div className="action-row"><button className="secondary-button big" disabled={busy} onClick={()=>event('STRIKER_SWITCH')}>Switch strike</button><button className="secondary-button big" disabled={busy} onClick={undo}>Undo last</button></div></section>
    <section className="card section"><div className="section-title">Extras</div><div className="action-row"><button className="extra-button" disabled={busy} onClick={()=>wide(0)}>Wide +1</button><button className="extra-button" disabled={busy} onClick={()=>wide(1)}>Wide +2</button><button className="extra-button" disabled={busy} onClick={()=>wide(2)}>Wide +3</button><button className="extra-button" disabled={busy} onClick={()=>noBall(0)}>No-ball +1</button><button className="extra-button" disabled={busy} onClick={()=>noBall(1)}>No-ball +2</button></div>{rules.coach&&<div className="action-row" style={{marginTop:10}}><button className="extra-button" disabled={busy} onClick={()=>event('COACH_THROW',{runs:0,unplayable:true})}>Unplayable</button><button className="extra-button" disabled={busy} onClick={()=>event('COACH_THROW',{runs:1,unplayable:true})}>Coach throw +1</button><button className="extra-button" disabled={busy} onClick={()=>event('COACH_THROW',{runs:2,unplayable:true})}>Coach throw +2</button></div>}</section>
    <section className="card section"><div className="section-title">Wicket / run out</div><div className="scoring-setup-grid"><div className="field"><label>Dismissal</label><select value={dismissal} onChange={e=>setDismissal(e.target.value)}><option>BOWLED</option><option>CAUGHT</option><option>STUMPED</option><option>LBW</option><option>HIT_WICKET</option><option>OBSTRUCTING_THE_FIELD</option></select></div><div className="field"><label>Fielder (optional)</label><select value={fielder} onChange={e=>setFielder(e.target.value)}><option value="">None</option>{fieldingPlayers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></div><div className="action-row"><button className="danger-button" disabled={busy} onClick={()=>wicket(dismissal)}>Record wicket</button><button className="secondary-button big" disabled={busy} onClick={runOut}>Run out (follow-up delivery)</button></div></section>
    <section className="card section"><div className="section-title">Current batters</div><div className="batters-grid"><div><strong>{name(state.striker_id)}</strong><small>{strikerStat?.runs??0} runs · {strikerStat?.balls??0} balls</small></div><div><strong>{name(state.non_striker_id)}</strong><small>{nonStat?.runs??0} runs · {nonStat?.balls??0} balls</small></div></div></section>
   </>}
   {current&&((rules.max&&current.total_balls>=rules.max)||state.pending_workflow==='INNINGS_COMPLETE')&&!completed&&<section className="card section target-card"><div className="section-title">Innings limit reached</div><p>{current.total_balls} balls recorded. End the innings to start the next innings.</p><button className="button" disabled={busy} onClick={completeInnings}>Complete innings</button></section>}
   {completed&&<section className="card section target-card"><div className="section-title">Match completed</div><p>The live scoring state is preserved. Finalisation and the professional match PDF are the next reporting layer.</p></section>}
   <section className="card section"><div className="section-title">Recent events</div><div className="event-list">{events.slice(0,12).map(e=><div className="event-row" key={e.id}><span>#{e.sequence_number}</span><strong>{e.event_type}</strong><span>{e.runs??0}</span><small>{new Date(e.created_at).toLocaleTimeString('en-ZA')}</small></div>)}</div></section>
 </div>
}
