'use client';
import {useState} from 'react';
import {MatchSquadClient} from '../../operations/matches/match-squad-client';
import {ScoringClient} from './scoring-client';
import {PauseMatchButton} from './pause-match-button';
type Player={id:string;team_id:string;batting_order:number|null;name:string};type ResumePlayer={player_id:string;team_id:string;jcm_players:{id:string;first_name:string;surname:string}|{id:string;first_name:string;surname:string}[]|null};type Selected={player_id:string;team_id:string;selected:boolean};type Team={id:string;name:string};
type Props={match:any;initialState:any;initialInnings:any[];players:Player[];initialEvents:any[];initialStats:any[];home:Team;away:Team;homePlayers:ResumePlayer[];awayPlayers:ResumePlayer[];selections:Selected[]};
function toScoringPlayers(rows:ResumePlayer[],ids:string[]){return rows.filter(p=>ids.includes(p.player_id)).map(p=>{const x=Array.isArray(p.jcm_players)?p.jcm_players[0]:p.jcm_players;return{id:p.player_id,team_id:p.team_id,batting_order:null,name:x?`${x.first_name} ${x.surname}`:'Player'}})}
export function ScoringPageClient({match,initialState,initialInnings,players,initialEvents,initialStats,home,away,homePlayers,awayPlayers,selections}:Props){const[resumed,setResumed]=useState(false);const[activePlayers,setActivePlayers]=useState(players);function confirmResume(a:string[],b:string[]){const next=toScoringPlayers(homePlayers,a).concat(toScoringPlayers(awayPlayers,b));setActivePlayers(next);setResumed(true)}return <>{!resumed&&<section className="card section"><div className="eyebrow">Resume check</div><h2>Select players for this session</h2><p className="subtitle">This selection is required every time a scorer opens or resumes the match. Scores, events, statistics, strike, bowler, over and workflow state remain in Supabase; this step selects the 6–14 players available for this session.</p><MatchSquadClient matchId={match.id} home={home} away={away} homePlayers={homePlayers} awayPlayers={awayPlayers} selections={selections} onResume={confirmResume}/></section>}{resumed&&<><ScoringClient match={match} initialState={initialState} initialInnings={initialInnings} players={activePlayers} initialEvents={initialEvents} initialStats={initialStats} homeName={home.name} awayName={away.name}/><PauseMatchButton matchId={match.id}/></>}</>}
